[build]
  command = "npm run build && npm run export"
  functions = "out_functions"
  publish   = "out_publish"

[[plugins]]
  package = "@netlify/plugin-sitemap"

# [[plugins]]
#   package = "./plugins/next-plugin"
