[build]
  command = "npm run build"
  functions = "out_functions"
  publish   = "out_publish"

[[plugins]]
  package = "@netlify/plugin-local-install-core"

[[plugins]]
  package = "@netlify/plugin-sitemap"

[[plugins]]
  package = "./next-plugin"
  [plugins.inputs]
    debug = true
