[build]
  command = "npm run build && npm run export"
  functions = "out_functions"
  publish   = "out_publish"

[[plugins]]
  package = "netlify-plugin-debug-cache"

[[plugins]]
  package = "@netlify/plugin-local-install-core"

[[plugins]]
  package = "@netlify/plugin-sitemap"

[[plugins]]
  package = "./plugins/next-plugin"
